services:
  # 1. KHỐI DATABASE (Đã xóa rò rỉ port 5432)
  db:
    image: postgres:15-alpine
    container_name: landingpage_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: landingpage_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. KHỐI BACKEND (Đã xóa rò rỉ port 8000)
  backend:
    build: ./backend
    container_name: landingpage_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:secretpassword@db:5432/landingpage_db
    depends_on:
      - db

  # 3. KHỐI FRONTEND (Đã xóa rò rỉ port 3000)
  frontend:
    build: ./frontend
    container_name: landingpage_frontend
    restart: always
    depends_on:
      - backend

  # 4. KHỐI BẢO VỆ NGINX (Chỉ mở duy nhất cổng 80 ra Internet)
  nginx:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: landingpage_proxy
      restart: always
      ports:
        - '80:80'   # Cổng HTTP
        - '443:443' # Cổng HTTPS (Bắt buộc để chạy SSL)
        - '81:81'   # Cổng quản lý Dashboard (Sau này xong thì đóng lại cho an toàn)
      volumes:
        - ./nginx/data:/data
        - ./nginx/letsencrypt:/etc/letsencrypt
      depends_on:
        - frontend
        - backend

volumes:
  pgdata: