services:
  # 1. KHỐI DATABASE (Đã xóa rò rỉ port 5432)
  db:
    image: postgres:15-alpine
    container_name: landingpage_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: landingpage_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. KHỐI BACKEND (Đã xóa rò rỉ port 8000)
  backend:
    build: ./backend
    container_name: landingpage_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:secretpassword@db:5432/landingpage_db
    depends_on:
      - db

  # 3. KHỐI FRONTEND (Đã xóa rò rỉ port 3000)
  frontend:
    build: ./frontend
    container_name: landingpage_frontend
    restart: always
    depends_on:
      - backend

  # 4. KHỐI BẢO VỆ NGINX (Chỉ mở duy nhất cổng 80 ra Internet)
  nginx:
    image: nginx:alpine
    container_name: landingpage_proxy
    restart: always
    ports:
      - "80:80" # Map cổng 80 của VPS vào cổng 80 của Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Bơm file cấu hình vào
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: