events {
    worker_connections 1024;
}

http {
    # 1. Định nghĩa các điểm đến nội bộ (Tên service trong Docker)
    upstream backend_api {
        server backend:8000;
    }

    upstream frontend_app {
        server frontend:80;
    }

    server {
        listen 80;
        
        # Có thể thay đổi '_ ' bằng domain thật sau này (vd: hydrosys.com)
        server_name _; 

        # 2. Bắt các request gửi đến /api và ném vào Backend
        location /api/ {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. Tất cả các request còn lại (giao diện) ném vào Frontend
        location / {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}